import collections
import math
try:
    import pandas as pd
except ImportError:
    pd = None

def calculate_entropy(data_series):
    counter = collections.Counter(data_series)
    total = sum(counter.values())
    if total == 0:
        return 0.0
    return -sum((count / total) * math.log2(count / total) for count in counter.values())

class FeatureEngineering:
    def __init__(self, db):
        self.db = db

    def generate_features(self):
        if not pd:
            print("[!] Pandas not installed, skipping feature generation.")
            return None
            
        # Get connections
        query_conns = "SELECT * FROM connections"
        df_conns = pd.read_sql(query_conns, self.db.engine)
        if df_conns.empty:
            return pd.DataFrame()
            
        # Get firewall events
        query_events = "SELECT * FROM firewall_events"
        df_events = pd.read_sql(query_events, self.db.engine)
        
        # Get alerts
        query_alerts = "SELECT * FROM alerts"
        df_alerts = pd.read_sql(query_alerts, self.db.engine)
        
        # Group connections by src_ip and build base features
        features = df_conns.groupby('src_ip').apply(lambda g: pd.Series({
            'connection_count': len(g),
            'unique_destination_ips': g['dst_ip'].nunique(),
            'unique_destination_ports': g['dst_port'].nunique(),
            'average_duration': g['duration'].mean(),
            'bytes_per_connection': g['bytes_out'].mean(),
            'packets_per_connection': g['packets_out'].mean(),
            'connection_rate': len(g) / (g['duration'].sum() or 1),
            'average_packet_rate': g['packets_out'].sum() / (g['duration'].sum() or 1),
            'bytes_per_second': g['bytes_out'].sum() / (g['duration'].sum() or 1),
            'packets_per_second': g['packets_out'].sum() / (g['duration'].sum() or 1),
            'protocol_entropy': calculate_entropy(g['protocol']),
            'destination_port_entropy': calculate_entropy(g['dst_port']),
            'active_hours': pd.to_datetime(g['creation_time']).dt.hour.nunique()
        })).reset_index()
        
        # Aggregate firewall events
        if not df_events.empty:
            event_agg = df_events.groupby('src_ip').apply(lambda g: pd.Series({
                'failed_connections': len(g[g['reason'].str.contains('fail', case=False, na=False)]),
                'blocked_connections': len(g[g['action'] == 'block'])
            })).reset_index()
            features = pd.merge(features, event_agg, on='src_ip', how='left')
        else:
            features['failed_connections'] = 0.0
            features['blocked_connections'] = 0.0
            
        # Aggregate alerts
        if not df_alerts.empty:
            df_alerts['timestamp'] = pd.to_datetime(df_alerts['timestamp'])
            alert_agg = df_alerts.groupby('src_ip').apply(lambda g: pd.Series({
                'alert_count': len(g),
                'alert_frequency': len(g) / ((g['timestamp'].max() - g['timestamp'].min()).total_seconds() or 1.0)
            })).reset_index()
            features = pd.merge(features, alert_agg, on='src_ip', how='left')
        else:
            features['alert_count'] = 0.0
            features['alert_frequency'] = 0.0
            
        # Get threat scores via API or join (currently threat_scoring is in-memory for testing, 
        # so we will use threat_intelligence table if it exists)
        query_threat = "SELECT * FROM threat_intelligence"
        df_threat = pd.read_sql(query_threat, self.db.engine)
        if not df_threat.empty:
            threat_agg = df_threat[['ip_address', 'threat_score']].rename(columns={'ip_address': 'src_ip'})
            features = pd.merge(features, threat_agg, on='src_ip', how='left')
        else:
            features['threat_score'] = 0.0
            
        # Fill NaNs generated by left joins
        features.fillna(0.0, inplace=True)
        
        # Convert necessary columns to appropriate numeric types
        numeric_cols = ['connection_count', 'unique_destination_ips', 'unique_destination_ports', 
                        'failed_connections', 'blocked_connections', 'alert_count', 'active_hours']
        features[numeric_cols] = features[numeric_cols].astype(int)
        
        return features
