"""Initial schema

Revision ID: c455b1d068ac
Revises: 
Create Date: 2026-06-26 08:23:20.745110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c455b1d068ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('src_ip', sa.String(), nullable=False),
    sa.Column('dst_ip', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_dst_ip'), 'alerts', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_alerts_src_ip'), 'alerts', ['src_ip'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_ip', sa.String(), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=False),
    sa.Column('dst_ip', sa.String(), nullable=False),
    sa.Column('dst_port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('packets_in', sa.Integer(), nullable=True),
    sa.Column('packets_out', sa.Integer(), nullable=True),
    sa.Column('bytes_in', sa.Integer(), nullable=True),
    sa.Column('bytes_out', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_creation_time'), 'connections', ['creation_time'], unique=False)
    op.create_index(op.f('ix_connections_dst_ip'), 'connections', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_connections_src_ip'), 'connections', ['src_ip'], unique=False)
    op.create_table('daily_traffic_aggregates',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=False),
    sa.Column('total_connections', sa.Integer(), nullable=False),
    sa.Column('total_packets', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('firewall_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('src_ip', sa.String(), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=False),
    sa.Column('dst_ip', sa.String(), nullable=False),
    sa.Column('dst_port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firewall_events_dst_ip'), 'firewall_events', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_firewall_events_src_ip'), 'firewall_events', ['src_ip'], unique=False)
    op.create_index(op.f('ix_firewall_events_timestamp'), 'firewall_events', ['timestamp'], unique=False)
    op.create_table('hourly_traffic_aggregates',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=False),
    sa.Column('total_connections', sa.Integer(), nullable=False),
    sa.Column('total_packets', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('src_ip', sa.String(), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=False),
    sa.Column('dst_ip', sa.String(), nullable=False),
    sa.Column('dst_port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('packet_size', sa.Integer(), nullable=True),
    sa.Column('flags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packets_dst_ip'), 'packets', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_packets_src_ip'), 'packets', ['src_ip'], unique=False)
    op.create_index(op.f('ix_packets_timestamp'), 'packets', ['timestamp'], unique=False)
    op.create_table('port_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('connections', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_statistics_timestamp'), 'port_statistics', ['timestamp'], unique=False)
    op.create_table('protocol_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('connections', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_statistics_timestamp'), 'protocol_statistics', ['timestamp'], unique=False)
    op.create_table('threat_intelligence',
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ip_address')
    )
    op.create_index(op.f('ix_threat_intelligence_threat_score'), 'threat_intelligence', ['threat_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_intelligence_threat_score'), table_name='threat_intelligence')
    op.drop_table('threat_intelligence')
    op.drop_index(op.f('ix_protocol_statistics_timestamp'), table_name='protocol_statistics')
    op.drop_table('protocol_statistics')
    op.drop_index(op.f('ix_port_statistics_timestamp'), table_name='port_statistics')
    op.drop_table('port_statistics')
    op.drop_index(op.f('ix_packets_timestamp'), table_name='packets')
    op.drop_index(op.f('ix_packets_src_ip'), table_name='packets')
    op.drop_index(op.f('ix_packets_dst_ip'), table_name='packets')
    op.drop_table('packets')
    op.drop_table('hourly_traffic_aggregates')
    op.drop_index(op.f('ix_firewall_events_timestamp'), table_name='firewall_events')
    op.drop_index(op.f('ix_firewall_events_src_ip'), table_name='firewall_events')
    op.drop_index(op.f('ix_firewall_events_dst_ip'), table_name='firewall_events')
    op.drop_table('firewall_events')
    op.drop_table('daily_traffic_aggregates')
    op.drop_index(op.f('ix_connections_src_ip'), table_name='connections')
    op.drop_index(op.f('ix_connections_dst_ip'), table_name='connections')
    op.drop_index(op.f('ix_connections_creation_time'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_src_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dst_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
